import { useEffect, useRef, useState } from 'react';
import { FaArrowDown, FaArrowUp, FaBars, FaBriefcase, FaCheck, FaCodeBranch, FaEnvelope, FaGithub, FaLinkedin, FaPhone, FaTimes } from 'react-icons/fa';

const nav = ['Home', 'About', 'Experience', 'Skills', 'Education', 'Projects', 'Contact'];
const skills: Record<string, string[]> = { Languages:['Java','JavaScript'], Frontend:['Vue.js','Vue 3','Angular','Thymeleaf'], Backend:['Spring Boot','Microservices','REST APIs'], 'CSS / UI':['Tailwind CSS','Bootstrap','Material UI','Shadcn'], Database:['MySQL','PostgreSQL','Oracle SQL'], Tools:['Docker','Git','GitHub','Postman','SVN'] };
const roles = [
  ['Software Engineer','Computer Network Systems (CNS) Limited','Nov 2022 — Present',['Java','Spring Boot','Vue.js','Angular','Docker'],['Designing and maintaining scalable backend systems and RESTful APIs.','Improving application performance, security, and reliability.','Contributing to scalable architecture and frontend integrations.']],
  ['Junior Software Engineer','Jobdesk','Mar 2022 — Oct 2022',['Java','Spring Boot','Angular'],['Contributed to enterprise web applications with Java and Spring Boot.','Worked with Angular applications as part of a full-stack engineering workflow.']]
];
const projects = [
  ['RAISE ERP','Featured enterprise system','A module-based ERP system for the Wage Earners’ Welfare Board, built around reintegration, financial assistance, payroll, accounting, HR, reporting, and more.',['Java Spring Boot','Vue.js 3','Tailwind CSS','Composition API','WebSocket'],'13 business modules'],
  ['Deeam Car Wash','Garage management system','A car wash and garage management system covering booking, scheduling, slots, clients, roles, memberships, chat, notifications, workflow, approvals, purchasing, and payments.',['Java Spring Boot','Vue.js 3'],'Operations & workflow'],
  ['Automated Vehicle Inspection System','BRTA system','A system supporting manual and automated vehicle inspection, including robotic-device inspections, booking, certificates, and schedule management.',['Java Spring Boot','Oracle','JasperReports','Vue.js 2','VueX','Bootstrap','SVN'],'Inspection workflows'],
  ['Collection of MV Tax','BRTA system','A system for calculating service-related payments for driving licences and vehicle registration, with payment management and bill generation.',['Java Spring Boot','Oracle','JasperReports','PostgreSQL','JDBC','Angular','SVN'],'Payments & billing'],
  ['BRTA Service Portal','Service platform','A platform supporting driving licence registration, vehicle fitness appointments, vehicle registration, service payments, and Jasper reporting.',['Java Spring MVC','Oracle','JSP','JavaScript','JasperReports','SVN'],'Citizen services']
];
function Title({n,eyebrow,title,copy}:{n:string;eyebrow:string;title:string;copy?:string}) { return <div className="section-title"><span>{n} / {eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div> }
function Logo() { return <span className="logo-mark" aria-hidden="true"><svg viewBox="0 0 42 42" fill="none"><path d="M7 13.5 15 7h15l5 7v15l-8 6H14l-7-7.5V13.5Z" fill="url(#logo-fill)"/><path d="M14 14.5 10.5 21l3.5 6.5M28 14.5 31.5 21 28 27.5" stroke="white" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/><path d="M18.5 15.5v11M16.3 15.5h4.4M16.3 26.5h4.4M24 15.5h3.2" stroke="white" strokeWidth="1.8" strokeLinecap="round"/><circle cx="31" cy="11" r="3" fill="#B8FFE2"/><defs><linearGradient id="logo-fill" x1="8" y1="6" x2="34" y2="36" gradientUnits="userSpaceOnUse"><stop stopColor="#2563EB"/><stop offset=".52" stopColor="#087F79"/><stop offset="1" stopColor="#0C665D"/></linearGradient></defs></svg></span> }
export default function App() {
 const [open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false),[sent,setSent]=useState(false);
 const [skillsProgress,setSkillsProgress]=useState(0);
 const skillsRef=useRef<HTMLElement>(null);
 useEffect(()=>{const f=()=>setScrolled(scrollY>20);addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]);
 useEffect(()=>{
  let frame=0;
  const updateSkills=()=>{
   frame=0;
   const section=skillsRef.current;
   if(!section) return;
   const {top}=section.getBoundingClientRect();
   const start=window.innerHeight*.88;
   const end=window.innerHeight*.2;
   setSkillsProgress(Math.min(1,Math.max(0,(start-top)/(start-end))));
  };
  const onScroll=()=>{if(!frame) frame=requestAnimationFrame(updateSkills)};
  updateSkills();
  addEventListener('scroll',onScroll,{passive:true});
  addEventListener('resize',onScroll);
  return()=>{removeEventListener('scroll',onScroll);removeEventListener('resize',onScroll);if(frame) cancelAnimationFrame(frame)};
 },[]);
 useEffect(()=>{
  const revealTargets=document.querySelectorAll('.section-title, .body-copy, .principles, .timeline-item, .skill-group, .education-grid article, .project, .contact-section > div, .contact-section form');
  revealTargets.forEach(target=>target.classList.add('reveal-on-scroll'));
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{
   if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}
  }),{threshold:.14});
  revealTargets.forEach(target=>observer.observe(target));
  return()=>observer.disconnect();
 },[]);
 const go=(id:string)=>{setOpen(false);document.getElementById(id.toLowerCase())?.scrollIntoView({behavior:'smooth'})};
 return <><header className={`site-header ${scrolled?'is-scrolled':''}`}><a className="brand" href="#home" onClick={()=>go('home')} aria-label="Ismail Tusher, home"><Logo/><span>Ismail Tusher</span></a><nav>{nav.map(x=><button key={x} onClick={()=>go(x)}>{x}</button>)}</nav><a className="nav-resume" href="mailto:tusher66@gmail.com?subject=Resume%20request">Request résumé <FaArrowDown/></a><button className="menu-button" onClick={()=>setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}>{open?<FaTimes/>:<FaBars/>}</button>{open&&<div className="mobile-nav">{nav.map(x=><button key={x} onClick={()=>go(x)}>{x}</button>)}</div>}</header>
 <main><section id="home" className="hero"><div className="hero-copy"><p className="kicker"><i/> Full-stack software engineer</p><h1>Engineering reliable systems for <em>real-world work.</em></h1><p className="hero-description">I’m Md. Ismail Hossain Tusher — a full-stack engineer with 3+ years of experience building scalable backend systems, RESTful APIs, and modern frontend applications.</p><div className="hero-actions"><button className="primary" onClick={()=>go('projects')}>Explore selected work <span>↗</span></button><button className="text-button" onClick={()=>go('contact')}>Let’s connect <span>→</span></button></div><div className="hero-meta"><span>Java / Spring Boot</span><span>Vue.js / Angular</span><span>Dhaka, Bangladesh</span></div></div><div className="architecture" aria-label="Abstract software architecture illustration"><div className="arch-top"><span>CLIENT</span><span className="active-dot">API</span><span>DATABASE</span></div><div className="arch-grid"><div className="arch-card"><small>01</small><strong>REST APIs</strong><p>Secure, scalable communication</p></div><div className="arch-card"><small>02</small><strong>Spring Boot</strong><p>Business logic & services</p></div><div className="arch-card"><small>03</small><strong>Modern UI</strong><p>Vue.js & Angular</p></div></div><div className="arch-line line-one"/><div className="arch-line line-two"/><div className="system-status"><i/> Systems thinking, end to end</div></div><button className="scroll-cue" onClick={()=>go('about')}><span>Scroll to explore</span><FaArrowDown/></button></section>
 <section id="about" className="section about-section"><div><Title n="01" eyebrow="About" title="Building with clarity, structure, and care."/><p className="body-copy">I focus on the parts of software that make products dependable: thoughtfully designed backend services, clean API contracts, data-driven systems, and frontend experiences that are easy to use. My work spans enterprise applications built with Java and Spring Boot, alongside Vue.js and Angular interfaces.</p><p className="body-copy">Across my professional experience, I have contributed to systems where maintainability, performance, and reliable delivery matter as much as features.</p></div><aside className="principles"><p className="label">Engineering focus</p><div><FaCodeBranch/><span><b>Backend foundations</b>Scalable services and RESTful APIs</span></div><div><FaBriefcase/><span><b>Enterprise context</b>Business workflows and connected systems</span></div><div><FaCheck/><span><b>Product-minded UI</b>Modern applications with practical usability</span></div></aside></section>
 <section id="experience" className="section tint"><Title n="02" eyebrow="Experience" title="Professional journey" copy="Building and supporting production software in Dhaka, Bangladesh."/><div className="timeline">{roles.map(([role,company,period,stack,points],i)=><article className="timeline-item" key={String(company)}><div className="timeline-date">{String(period)}</div><div className="timeline-dot">0{i+1}</div><div className="experience-card"><p className="label">{String(company)}</p><h3>{String(role)}{i===0&&<span className="current">Current</span>}</h3><ul>{(points as string[]).map(p=><li key={p}>{p}</li>)}</ul><div className="tags">{(stack as string[]).map(s=><span key={s}>{s}</span>)}</div></div></article>)}</div></section>
 <section id="skills" className="section skills-section" ref={skillsRef}><Title n="03" eyebrow="Capabilities" title="A practical, modern stack." copy="Technologies used across backend systems, frontend applications, and the day-to-day engineering toolkit."/><div className="skill-grid">{Object.entries(skills).map(([cat,vals],i)=>{const reveal=Math.min(1,Math.max(0,(skillsProgress-i*.1)/.56));return <article className="skill-group skill-scroll-reveal" key={cat} style={{'--skill-reveal':reveal} as React.CSSProperties}><span className="skill-number">0{i+1}</span><h3>{cat}</h3><div>{vals.map(s=><span className="skill-chip" key={s}>{s}</span>)}</div></article>})}</div></section>
 <section id="education" className="section education-section"><Title n="04" eyebrow="Education" title="Academic foundation"/><div className="education-grid"><article><p className="label">Bachelor’s degree</p><h3>B.Sc. in Information and Communication Engineering</h3><p>Bangladesh Army University of Engineering and Technology (BAUET)</p><footer>Qadirabad Cantonment, Natore <b>CGPA 3.54 / 4.00</b></footer></article><article><p className="label">Higher secondary</p><h3>Higher Secondary Certificate</h3><p>Govt. Shahid BulBul College, Pabna</p></article></div></section>
 <section id="projects" className="section projects-section"><Title n="05" eyebrow="Selected work" title="Enterprise software, made tangible." copy="A selection of systems demonstrating experience across backend architecture, operations, reporting, payments, and service delivery."/><div className="project-list">{projects.map(([title,eyebrow,description,tech,feature],i)=><article className="project" key={String(title)}><div className="project-index">0{i+1}</div><div className="project-main"><p className="label">{String(eyebrow)}</p><h3>{String(title)}</h3><p>{String(description)}</p></div><div className="project-detail"><span>{String(feature)}</span><div className="tags">{(tech as string[]).map(s=><span key={s}>{s}</span>)}</div></div></article>)}</div><div className="more-projects"><p className="label">Additional project work</p>{['CPA Conversion','CMS for SBC and IDRA','Aptitudo','Cultural Transformation System','JobDesk'].map(x=><span key={x}>{x}</span>)}</div></section>
 <section id="contact" className="contact-section"><div><p className="kicker"><i/> Contact</p><h2>Let’s build something <em>meaningful.</em></h2><p>For full-stack engineering opportunities or a conversation about your next software project, feel free to get in touch.</p><div className="contact-links"><a href="mailto:tusher66@gmail.com"><FaEnvelope/> tusher66@gmail.com</a><a href="tel:+8801754343120"><FaPhone/> +880 1754-343120</a><a href="https://github.com/Tusher66" target="_blank" rel="noreferrer"><FaGithub/> GitHub</a><a href="https://www.linkedin.com/in/ismail-hossain-tusher" target="_blank" rel="noreferrer"><FaLinkedin/> LinkedIn</a></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@company.com"/></label><label>Subject<input required placeholder="How can I help?"/></label><label>Message<textarea required rows={4} placeholder="Tell me a little about the opportunity or project."/></label><button className="primary" type="submit">{sent?'Message ready — thank you':'Send message'} <span>↗</span></button><p className="form-note">This form is ready to connect to your preferred email or API service.</p></form></section></main>
 <footer className="site-footer"><a className="brand" href="#home" onClick={()=>go('home')} aria-label="Back to home"><Logo/><span>Md. Ismail Hossain Tusher</span></a><p>Full-Stack Software Engineer</p><p>© {new Date().getFullYear()}</p><button onClick={()=>go('home')}>Back to top <FaArrowUp/></button></footer></>;
}
